# Generated by Django 3.2.14 on 2022-08-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_vip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vip_id',
            field=models.IntegerField(default=0),
        ),
    ]
