# Generated by Django 3.2.14 on 2022-08-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vip_id',
            field=models.IntegerField(default=2),
        ),
    ]
